# Generated by Django 2.2.7 on 2020-01-06 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('bet_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('teama', models.CharField(max_length=50)),
                ('teamb', models.CharField(max_length=50)),
                ('oddsa', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('oddsx', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('oddsb', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('game_date', models.DateField(verbose_name='game_date')),
                ('finalscore', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacedBet',
            fields=[
                ('placed_bet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pick', models.CharField(max_length=50)),
                ('is_won', models.BooleanField(blank=True, default=None, null=True)),
                ('bet_id', models.ManyToManyField(to='bets.Bet')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('stake', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('is_placed', models.BooleanField(default=False)),
                ('status', models.BooleanField(blank=True, default=None, null=True)),
                ('placedbets', models.ManyToManyField(to='bets.PlacedBet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
